theme = "native"
icons = "awesome"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "custom"
command = "cat ~/.cache/pomo.cache"
signal = 4
interval = "once"
hide_when_empty = false

[[block]]
block = "music"
#buttons = ["prev", "next"]
interface_name_exclude = [".*kdeconnect.*", "mpd", "chromium*"]
max_width = 25
dynamic_width = true
# smart_trim = true
hide_when_empty	= true
on_click = "playerctl --player=spotify,cmus,%any play-pause"

# [[block]]
# block = "docker"
# interval = 2
# format = "{running}/{total}"

[[block]]
block = "backlight"
device = "intel_backlight"
step_width = 10
root_scaling = 2

[[block]]
block = "sound"

# [[block]]
# block = "networkmanager"
# on_click = "$TERMINAL -e nmtui connect"
# device_format= "{icon}{ap}"
# interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
# interface_name_include = []

[[block]]
block = "weather"
format = "{weather} {temp}"
service = { name = "openweathermap", api_key = "c9594a53527d5db3dd809f5c0f32315c", city_id = "4561628", units = "imperial" }   # Swarthmore
#service = { name = "openweathermap", api_key = "c9594a53527d5db3dd809f5c0f32315c", city_id = "5380748", units = "imperial" }  # Palo Alto

# [[block]]
# block = "maildir"
# interval = 60
# inboxes = ["/home/nitay/.local/share/mail/yatin.lala@gmail.com/INBOX"]
# threshold_warning = 1
# threshold_critical = 10
# display_type = "new"

[[block]]
block = "time"
interval = 60
format = "%a %m/%d %I:%M %P"

[[block]]
block = "battery"
interval = 5
format = " {percentage}"
