#!/usr/bin/dash

set -e

output=" "

if pgrep -x spotify > /dev/null; then
  output="$output  "
fi
if pgrep -x signal-desktop > /dev/null; then
   output="$output  "
fi

output="$output "

echo "$output"
