#!/bin/sh

choices="dunst\nespanso\ni3\ni3status\nlf\nnvim\npicom\nxinitrc\nxresources\nzathura\nzshrc\nzsh aliases"
chosen=$(echo -e "$choices" | rofi -dmenu -i -p "config menu")

case $chosen in
    dunst) urxvtc -e $EDITOR $XDG_CONFIG_HOME/dunst/dunstrc;;
    espanso) urxvtc -e $EDITOR $XDG_CONFIG_HOME/espanso/default.yml;;
    i3) urxvtc -e $EDITOR $XDG_CONFIG_HOME/i3/config;;
    i3status) urxvtc -e $EDITOR $XDG_CONFIG_HOME/i3status/config;;
    lf) urxvtc -e $EDITOR $XDG_CONFIG_HOME/lf/lfrc;;
    nvim) urxvtc -e $EDITOR $XDG_CONFIG_HOME/nvim/init.vim;;
    picom) urxvtc -e $EDITOR $XDG_CONFIG_HOME/picom/picom.conf;;
    xinitrc) urxvtc -e $EDITOR $XDG_CONFIG_HOME/X11/xinitrc;;
    xresources) urxvtc -e $EDITOR $XDG_CONFIG_HOME/X11/Xresources;;
    zathura) urxvtc -e $EDITOR $XDG_CONFIG_HOME/zathura/zathurarc;;
    zshrc) urxvtc -e $EDITOR $XDG_CONFIG_HOME/zsh/.zshrc;;
    "zsh aliases") urxvtc -e $EDITOR $XDG_CONFIG_HOME/zsh/aliases;;
esac
