#!/bin/bash

# if [ -f ~/.cache/newsboat.log ]; then
#     now=$(date +%s)
#     last=$(stat -c %Y ~/.cache/newsboat.log)
#     diff=$((now - last))
#     (( diff > 1800 )) && /usr/bin/newsboat || notify-send "$((diff / 60)) minutes since last invocation"
#     echo "$(date '+%Y-%m-%d %H:%M:%S') $*" > ~/.cache/newsboat.log
# else
#     echo "$(date '+%Y-%m-%d %H:%M:%S') $*" > ~/.cache/newsboat.log
#     /usr/bin/newsboat
# fi


log_file=~/.cache/newsboat.log

if [ -f "$log_file" ]; then
    now=$(date +%s)
    last=$(stat -c %Y "$log_file")
    diff=$((now - last))

    if [ "$diff" -gt 1800 ]; then
        /usr/bin/newsboat
    else
        notify-send "$((diff / 60)) minutes since last invocation"
    fi
else
    /usr/bin/newsboat
    echo "$(date +%Y-%m-%d' '%H:%M:%S) $*" > "$log_file"
fi

