#!/usr/bin/env bash

# Get the current date or use the provided date
DATE=${2:-$(date +"%Y-%m-%d")}
FILE_DATE=$(date -d "$DATE" +"%m/%d/%y")
DIARY_DIR="$HOME/documents/org/diary"
FILE_PATH="$DIARY_DIR/$DATE.org"

# Generate the file if it doesn't exist
generate_file() {
  if [ ! -f "$FILE_PATH" ]; then
    echo "$FILE_DATE" > "$FILE_PATH"
    echo "" >> "$FILE_PATH"
    echo "meals:" >> "$FILE_PATH"
    echo "" >> "$FILE_PATH"
    echo "total: " >> "$FILE_PATH"
    echo "goal: 110g" >> "$FILE_PATH"
    echo "needed: " >> "$FILE_PATH"
  fi
}

# Parse options
if [[ "$1" == "-gen" ]]; then
  generate_file
  echo "File generated at $FILE_PATH"
else
  generate_file
  # Open the file in Neovim
  exec nvim "$FILE_PATH"
fi
