#!/bin/sh

status=$(nmcli radio wifi)

case $status in
    enabled) 
        notify-send "WIFI RADIO DISABLED"
        nmcli radio wifi off;;
    disabled) 
        notify-send "WIFI RADIO ENABLED"
        nmcli radio wifi on;;
esac
