#!/bin/bash -e

# Install base utilities
sudo pacman -Syu neovim xorg xorg-xinit i3-gaps i3status-rust base-devel

pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si
