#!/bin/sh

cd ~

export WM='sway'
export _JAVA_AWT_WM_NONREPARENTING=1
export XCURSOR_SIZE=24
export CLUTTER_BACKEND=wayland 
export XDG_SESSION_TYPE=wayland 
export QT_WAYLAND_DISABLE_WINDOWDECORATION=1 
export MOZ_ENABLE_WAYLAND=1 
export WLR_NO_HARDWARE_CURSORS=1 
export WLR_BACKEND=vulkan 
export QT_QPA_PLATFORM=wayland 
export GDK_BACKEND=wayland 

systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

exec sway
