#!/usr/bin/env bash

# Only one instance of this script is guaranteed to run.
function run {
  if ! pgrep -f $1 ;
  then
    $@&
  fi
}

# Add desired autorun startup programs with arguments.
pulseaudio-startup-script &
picom &
urxvtd -q &
dunst &
# redshift &
nm-applet &
