#!/usr/bin/sh -e

choices="dunstrc\nespanso\ni3\ni3status\nlfrc\nmpv.conf\nmpv input.conf\nnewsboat config\nnewsboat urls\nnvim\npicom\nsway\nxinitrc\nxresources\nzathura\nzshenv\nzshrc\nzsh aliases"
chosen=$(echo "$choices" | rofi -dmenu -i -p "config menu")

case $chosen in
    dunstrc) urxvtc -e $EDITOR $XDG_CONFIG_HOME/dunst/dunstrc;;
    espanso) urxvtc -e $EDITOR $XDG_CONFIG_HOME/espanso/default.yml;;
    i3) urxvtc -e $EDITOR $XDG_CONFIG_HOME/i3/config;;
    i3status) urxvtc -e $EDITOR $XDG_CONFIG_HOME/i3status-rust/config.toml;;
    lfrc) urxvtc -e $EDITOR $XDG_CONFIG_HOME/lf/lfrc;;
    mpv.conf) urxvtc -e $EDITOR $XDG_CONFIG_HOME/mpv/mpv.conf;;
    "mpv input.conf") urxvtc -e $EDITOR $XDG_CONFIG_HOME/mpv/input.conf;;
    "newsboat config") urxvtc -e $EDITOR $XDG_CONFIG_HOME/newsboat/config;;
    "newsboat urls") urxvtc -e $EDITOR $XDG_CONFIG_HOME/newsboat/urls;;
    nvim) urxvtc -e $EDITOR $XDG_CONFIG_HOME/nvim/init.vim;;
    picom) urxvtc -e $EDITOR $XDG_CONFIG_HOME/picom/picom.conf;;
    sway) urxvtc -e $EDITOR $XDG_CONFIG_HOME/sway/config;;
    termite) urxvtc -e $EDITOR $XDG_CONFIG_HOME/termite/config;;
    xinitrc) urxvtc -e $EDITOR $XDG_CONFIG_HOME/X11/xinitrc;;
    xresources) urxvtc -e $EDITOR $XDG_CONFIG_HOME/X11/Xresources;;
    zathura) urxvtc -e $EDITOR $XDG_CONFIG_HOME/zathura/zathurarc;;
    zshenv) urxvtc -e $EDITOR $XDG_CONFIG_HOME/zsh/.zshenv;;
    zshrc) urxvtc -e $EDITOR $XDG_CONFIG_HOME/zsh/zshrc;;
    "zsh aliases") urxvtc -e $EDITOR $XDG_CONFIG_HOME/zsh/aliases;;
esac
