#!/bin/sh -e

choices="internal\nhdmi\nmanual"
chosen=$(echo "$choices" | rofi -dmenu -i -p "display menu")

case $chosen in
    internal) xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output VIRTUAL1 --off;;
    hdmi) xrandr --output eDP1 --primary --mode 1920x1080 --pos 1920x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --mode 1920x1080 --pos 0x0 --rotate normal --output VIRTUAL1 --off;;
    manual) arandr;;
esac
