#!/usr/bin/env bash

echo "" > $XDG_CACHE_HOME/gammadark.cache

notify-send "Start work!"

pkill -SIGRTMIN+4 i3status-rs

nmcli device disconnect wlp0s20f3

min=5
sec=0

while [ $min -ge 0 ]; do
    while [ $sec -ge 0 ]; do
        echo " $min:$sec" > $XDG_CACHE_HOME/pomo.cache
        pkill -SIGRTMIN+4 i3status-rs
        let "sec=sec-1"
        wifi off
        sleep 1
    done
    sec=59
    let "min=min-1"
done

echo "" > $XDG_CACHE_HOME/pomo.cache
pkill -SIGRTMIN+4 i3status-rs

wifi on

notify-send "Done!"
