#!/usr/bin/env bash

# TODO nvim integration with util.toggleBg().
# TODO light and dark should be separate abstractions from colorscheme
# cache file could be: <colorscheme> <light>|<dark>

lark=$(<"$XDG_CACHE_HOME/lark.cache")

case $1 in
print) echo "$lark" ;;
toggle)
	case $lark in
	gruvbox-light-medium)
		echo "gruvbox-dark-medium" >"$XDG_CACHE_HOME/lark.cache"
		theme.sh "$(<"$XDG_CACHE_HOME/lark.cache")"
		;;
	gruvbox-dark-medium)
		echo "gruvbox-light-medium" >"$XDG_CACHE_HOME/lark.cache"
		theme.sh "$(<"$XDG_CACHE_HOME/lark.cache")"
		;;
	*)
		echo "gruvbox-light-medium" >"$XDG_CACHE_HOME/lark.cache"
		theme.sh "$(<"$XDG_CACHE_HOME/lark.cache")"
		;;
	esac
	;;
*) echo "invalid input" ;;
esac
