#!/usr/bin/env sh

acc='yatin.lala@gmail.com'

mbsync -c /home/nitay/.config/mbsyncrc -a

new=$(find "$HOME/.local/share/mail/$acc/INBOX/new/" "$HOME/.local/share/mail/$acc/Inbox/new/" "$HOME/.local/share/mail/$acc/inbox/new/" -type f -newer "${XDG_CONFIG_HOME:-$HOME/.config}/mutt/.mailsynclastrun" 2> /dev/null)
newcount=$(echo "$new" | sed '/^\s*$/d' | wc -l)
notify-send "$newcount new email(s)."
