#!/usr/bin/env bash

echo "" > $XDG_CACHE_HOME/pomo.cache

notify-send "Start work!"

wifi off

min=5
sec=0

while [ $min -ge 0 ]; do
    while [ $sec -ge 0 ]; do
        echo " $min:$sec" > $XDG_CACHE_HOME/pomo.cache
        pkill -SIGRTMIN+4 i3status-rs
        let "sec=sec-1"
        sleep 1
    done
    sec=59
    let "min=min-1"
done

echo "" > $XDG_CACHE_HOME/pomo.cache

wifi on

notify-send "Done!"
