#!/usr/bin/sh -e
chosen=$(echo -e "mount cslab\nmount ibis\nunmount cslab\nunmount ibis\ninternal\nhdmi\nmanual" | rofi -matching fuzzy -dmenu -i -p "ssh & display menu")
case $chosen in
    "mount cslab") sshfs ylala1@lab.cs.swarthmore.edu:/home/ylala1 ~/.local/mount/cslab;;
    "unmount cslab") fusermount3 -uqz ~/.local/mount/cslab;;
    "mount ibis") sshfs s-ylala1@ibis.sccs.swarthmore.edu:/ ~/.local/mount/ibis;;
    "unmount ibis") fusermount3 -uqz ~/.local/mount/ibis;;
    internal) xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x0 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --off --output VIRTUAL1 --off;;
    hdmi) xrandr --output eDP1 --primary --mode 1920x1080 --pos 0x408 --rotate normal --output DP1 --off --output DP2 --off --output HDMI1 --mode 1920x1080 --pos 1920x0 --rotate normal --output VIRTUAL1 --off
        i3-msg move workspace to output HDMI1;;
    manual) arandr;;
esac
