#!/bin/sh -e

chosen=$(echo -e "cs-lab\nibis\nowl" | rofi -dmenu -i -p "ssh menu")
case $chosen in
    cs-lab) $TERMINAL -e ssh ylala1@lab.cs.swarthmore.edu;;
    ibis) $TERMINAL -e ssh s-ylala1@ibis.sccs.swarthmore.edu;;
    owl) ssh ylala1@owl.cs.swarthmore.edu;;
esac
