#!/usr/bin/zsh -e

echo  "[a]wesome [b]spwm [i]3wm [s]way"

read input

if [ "$input" = "a" ]
then
    startx "$HOME/.config/X11/xinitrc.awesome"
elif [ "$input" = "b" ]
then
    startx "$HOME/.config/X11/xinitrc.bspwm"
elif [ "$input" = "i" ]
then
    startx "$HOME/.config/X11/xinitrc.i3"
else
    sway
fi
