#!/usr/bin/sh

# Import the WAYLAND_DISPLAY env var from sway into the systemd user session.
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=sway

# Stop any services that are running, so that they receive the new env var when they restart.
systemctl --user stop pipewire wireplumber xdg-desktop-portal xdg-desktop-portal-wlr
systemctl --user start wireplumber

# Get mouse cursor theme to be respected
# gsettings set org.gnome.desktop.interface cursor-theme "Breeze_Snow"

# import-gsettings
