#!/usr/bin/sh -e
TERMINAL='alac'
case $1 in
    bc)
        pgrep -x bc || $TERMINAL -name calc -e bc -q
        i3-msg "[instance=calc] scratchpad show; [instance=calc] move position center";;
    blueman-manager)
        pgrep -x "blueman-manager" && killall blueman-manager || setsid blueman-manager &;;
    bluetooth)
        rfkill unblock 0
        pgrep -x bluetoothctl || ($TERMINAL --class bluetooth -e bluetoothctl && sleep .1)
        i3-msg "[instance=bluetooth] scratchpad show; [instance=bluetooth] move position center";;
    calendar)
        wmctrl -l | grep -q "pointer Calendar - SCCS Nextcloud" || \
        (gtk-launch calendar; sleep 1)
        i3-msg "[instance=crx_gipedbjkhfgkohfgefhoabnbnbomkjkc] scratchpad show; \
        [instance=crx_gipedbjkhfgkohfgefhoabnbnbomkjkc] move position center";;
    cmus)
        pgrep -x cmus || ($TERMINAL --class cmus -e cmus && sleep .1)
        i3-msg "[instance=cmus] scratchpad show; [instance=cmus] move position center";;
    discord)
        pgrep -x discord || setsid discord &
        i3-msg "[class=discord] focus";;
    espanso)
        pgrep -x espanso && (espanso stop; notify-send -t 1000 "Espanso stopped.") || \
        setsid espanso daemon &;;
    gmail)
        wmctrl -l | grep -q "pointer Gmail" || \
        (gtk-launch gmail; sleep 1)
        i3-msg "[instance=crx_fmgjjmmmlfnkbppncabfkddbjimcfncm] scratchpad show; \
        [instance=crx_fmgjjmmmlfnkbppncabfkddbjimcfncm] move position center";;
    habitica)
        wmctrl -l | grep -q "pointer Habitica" || (gtk-launch habitica; sleep 1)
        i3-msg "[instance=crx_pdigihnmoiplkhocekidmdcmhchhdpjo] scratchpad show; [instance=crx_pdigihnmoiplkhocekidmdcmhchhdpjo] move position center";;
    mailspring)
        (pgrep -x mailspring && (wmctrl -l | grep -q "pointer Mailspring" || \
        setsid mailspring &)) || setsid mailspring &
        i3-msg "[class=Mailspring] focus";;
    music)
        pgrep -x "spotify|cmus|spotifyd" && playerctl --player=spotify,cmus,spotifyd play-pause || \
        i3-msg mode "Action: [a]udacity rofi-[b]eats [c]mus [r]eaper [s]potify spotify-[t]ui";;
    nextcloud) pgrep -x "nextcloud" && killall nextcloud || setsid nextcloud &;;
    nm-applet)
        pgrep -x "nm-applet" && killall nm-applet || setsid nm-applet &;;
    notes)
        wmctrl -l | grep -q "pointer notes" || \
        # swaymsg -t get_tree | grep "\"app_id\": \"notes\"" || \
        $TERMINAL --class notes --title notes -e nvim ~/documents/wiki/index.md && sleep 0.1
        i3-msg "[instance=notes] scratchpad show; [instance=notes] move position center";;
    pavucontrol)
        pgrep -x "pavucontrol" || setsid pavucontrol &
        i3-msg "[title=pavucontrol] scratchpad show; [title=pavucontrol] move position center";;
    pulsemixer)
        pgrep -x pulsemixer || ($TERMINAL --class pulsemixer -e pulsemixer && sleep .1)
        i3-msg "[instance=pulsemixer] scratchpad show; [instance=pulsemixer] move position center";;
    redshift)
        pgrep -x "redshift" && (killall redshift; notify-send -t 1000 "Killing redshift.") || \
        (notify-send -t 1000 "Starting Redshift."; setsid redshift -b 1:1);;
    redshift-dark)
        pgrep -x "redshift" && (killall redshift; notify-send -t 1000 "Killing redshift.") || \
        (notify-send -t 1000 "Starting Redshift."; setsid redshift -b 1:.6);;
    signal)
        pgrep -x signal-desktop || setsid signal-desktop &
        i3-msg "[class=Signal] focus";;
    spotify)
        pgrep -x "spotify" || spotify &
        i3-msg "[instance=spotify] scratchpad show; [instance=spotify] move position center";;
    spotifyd)
        pgrep -x spotifyd && (notify-send -t 1000 "Killing spotifyd."; killall spotifyd) || \
        (notify-send -t 1000 "Starting spotifyd."; setsid spotifyd &);;
    spotify-tui)
        pgrep -x "spotifyd" || spotifyd &
        pgrep -x spt || ($TERMINAL --class spt -e spt && sleep .1)
        i3-msg "[instance=spt] scratchpad show; [instance=spt] move position center";;
    tmux);;
    todoist)
        wmctrl -l | grep -q "pointer Todoist" || (gtk-launch todoist; sleep 1)
        i3-msg "[instance=crx_elldfnmogicegdcphgljaoaklkpcnbnn] scratchpad show; [instance=crx_elldfnmogicegdcphgljaoaklkpcnbnn] move position center";;
    whatsapp)
        wmctrl -l | grep -q "pointer WhatsApp" || (gtk-launch whatsapp; sleep 1)
        i3-msg workspace 9;;
    *) echo "Invalid argument.";;
esac
