#!/usr/bin/sh -e
TERMINAL='urxvtc'
case $1 in
    bc)
        pgrep -x bc || $TERMINAL -name calc -title calc -e bc -q
        i3-msg "[instance=calc] scratchpad show; [instance=calc] move position center";;
    bluetooth)
        rfkill unblock 0
        wmctrl -l | grep -q "pointer bluetooth" || \
        # swaymsg -t get_tree | grep "\"app_id\": \"notes\"" || \
        $TERMINAL -name bluetooth -title bluetooth -e bluetoothctl
        i3-msg "[title="bluetooth"] scratchpad show; [title="bluetooth"] move position center";;
    calendar)
        wmctrl -l | grep -q "pointer Google Calendar -" || \
        (gtk-launch calendar; sleep 1)
        i3-msg "[instance=crx_kjbdgfilnfhdoflbpgamdcdgpehopbep] scratchpad show; \
        [instance=crx_kjbdgfilnfhdoflbpgamdcdgpehopbep] move position center";;
    espanso)
        pgrep -x espanso && (espanso stop; notify-send "Espanso stopped.") || \
        setsid espanso daemon &;;
    gmail)
        wmctrl -l | grep -q "pointer Gmail" || \
        (gtk-launch gmail; sleep 1)
        i3-msg "[instance=crx_fmgjjmmmlfnkbppncabfkddbjimcfncm] scratchpad show; \
        [instance=crx_fmgjjmmmlfnkbppncabfkddbjimcfncm] move position center";;
    mailspring)
        (pgrep -x mailspring && (wmctrl -l | grep -q "pointer Mailspring" || \
        setsid mailspring &)) || setsid mailspring &
        i3-msg workspace 1;;
    music)
        pgrep -x "spotify|cmus|spotifyd" && playerctl --player=spotify,cmus,spotifyd play-pause || \
        i3-msg mode "Action: [a]udacity rofi-[b]eats [c]mus s[p]otify-tui [r]eaper [s]potify";;
    nextcloud) pgrep -x "nextcloud" && killall nextcloud || setsid nextcloud &;;
    nm-applet)
        pgrep -x "nm-applet" && killall nm-applet || setsid nm-applet &;;
    notes)
        wmctrl -l | grep -q "pointer notes" || \
        # swaymsg -t get_tree | grep "\"app_id\": \"notes\"" || \
        $TERMINAL -name notes -title notes -e nvim ~/documents/wiki/index.md && sleep 0.05
        i3-msg "[title="notes"] scratchpad show; [title="notes"] move position center";;
    redshift)
        pgrep -x "redshift" && (killall redshift; notify-send "Killing redshift.") || \
        (notify-send "Starting Redshift."; setsid redshift -b 1:1);;
    redshift-dark)
        pgrep -x "redshift" && (killall redshift; notify-send "Killing redshift.") || \
        (notify-send "Starting Redshift."; setsid redshift -b 1:.5);;
    spotifyd)
        pgrep -x spotifyd && (notify-send "Killing spotifyd."; killall spotifyd) || \
        (notify-send "Starting spotifyd."; setsid spotifyd &);;
    spotify-tui)
        pgrep -x "spotifyd" || spotifyd &
        pgrep -x spt || $TERMINAL -t spt --class spt -e spt
        i3-msg workspace 9;;
    tmux);;
    todoist)
        wmctrl -l | grep -q "pointer Todoist" || (gtk-launch todoist; sleep 1)
        i3-msg "[instance="crx_elldfnmogicegdcphgljaoaklkpcnbnn"] scratchpad show; [instance="crx_elldfnmogicegdcphgljaoaklkpcnbnn"] move position center";;
    whatsapp)
        wmctrl -l | grep -q "pointer WhatsApp" || (gtk-launch whatsapp; sleep 1)
        i3-msg workspace 8;;
    *) echo "Invalid argument.";;

    *) echo "Invalid argument.";;
esac
