#!/usr/bin/sh -e
TERMINAL='urxvtc'
case $1 in
    bc)
        pgrep -x bc || $TERMINAL -name calc -title calc -e bc -q
        i3-msg "[instance=calc] scratchpad show; [instance=calc] move position center";;
    calendar)
        wmctrl -l | grep -q "point Google Calendar -" || \
        (gtk-launch calendar; sleep 1)
        i3-msg "[instance=crx_kjbdgfilnfhdoflbpgamdcdgpehopbep] scratchpad show; \
        [instance=crx_kjbdgfilnfhdoflbpgamdcdgpehopbep] move position center";;
    espanso)
        pgrep -x espanso && (espanso stop; notify-send "Espanso stopped.") || \
        setsid espanso daemon &;;
    gmail)
        wmctrl -l | grep -q "point Gmail" || \
        (gtk-launch gmail; sleep 1)
        i3-msg "[instance=crx_fmgjjmmmlfnkbppncabfkddbjimcfncm] scratchpad show; \
        [instance=crx_fmgjjmmmlfnkbppncabfkddbjimcfncm] move position center";;
    mailspring)
        (pgrep -x mailspring && (wmctrl -l | grep -q "point Mailspring" || \
        setsid mailspring &)) || setsid mailspring &
        i3-msg workspace 1;;
    music)
        pgrep -x "spotify|cmus|spotifyd" && playerctl --player=spotify,cmus,spotifyd play-pause || \
        i3-msg mode "Action: [a]udacity rofi-[b]eats [c]mus s[p]otify-tui [r]eaper [s]potify";;
    nm-applet)
        pgrep -x "nm-applet" && killall nm-applet || setsid nm-applet &;;
    notes)
        wmctrl -l | grep -q "point notes" || \
        # swaymsg -t get_tree | grep "\"app_id\": \"notes\"" || \
        $TERMINAL -name notes -title notes -e nvim ~/documents/wiki/index.md && sleep 0.05
        i3-msg "[title="notes"] scratchpad show; [title="notes"] move position center";;
    redshift)
        pgrep -x "redshift" && (killall redshift; notify-send "Killing redshift.") || \
        (notify-send "Starting Redshift."; setsid redshift -b 1:.6);;
    spotifyd)
        pgrep -x spotifyd && (notify-send "Killing spotifyd."; killall spotifyd) || \
        (notify-send "Starting spotifyd."; setsid spotifyd &);;
    spotifyd-spt) 
        (killall -q spotifyd && setsid spotifyd &) || setsid spotifyd &
        (killall -q spt && i3-msg 'workspace 10') || i3-msg 'workspace 10'
        $TERMINAL -name spt -title spt -e spt;;
    spotify-tui)
        pgrep -x "spotifyd" || spotifyd &
        pgrep -x spt || $TERMINAL -t spt --class spt -e spt
        i3-msg workspace 10;;
    todoist)
        wmctrl -l | grep -q "point Todoist" || (gtk-launch todoist; sleep 1)
        i3-msg "[instance="crx_elldfnmogicegdcphgljaoaklkpcnbnn"] scratchpad show; [instance="crx_elldfnmogicegdcphgljaoaklkpcnbnn"] move position center";;
    *) echo "Invalid argument.";;
esac
