#!/usr/bin/sh -e

paru

pacman -Qqe | grep -v "$(pacman -Qqm)" > ~/.dotfiles/pkglist/pacman
pacman -Qqm > ~/.dotfiles/pkglist/aur

npm -g update

# RESTORE
# cat pacman | xargs pacman -S --needed --noconfirm
