#!/usr/bin/sh -e

status=$(nmcli radio wifi)

case $status in
    enabled) 
        nmcli radio wifi off
        notify-send "Wifi radios disabled.";;
    disabled) 
        nmcli radio wifi on
        notify-send "Wifi radios enabled.";;
esac
