#!/bin/sh

status=$(nmcli radio wifi)

case $status in
    enabled) 
        nmcli radio wifi off
        notify-send "Wifi radio disabled.";;
    disabled) 
        nmcli radio wifi on
        notify-send "Wifi radio enabled.";;
esac
