vim.pack.add({ "https://github.com/lewis6991/gitsigns.nvim" })

vim.keymap.set("n", "<leader>gj", function()
    require("gitsigns").next_hunk()
end, { desc = "Next Hunk" })
vim.keymap.set("n", "<leader>gk", function()
    require("gitsigns").prev_hunk()
end, { desc = "Previous Hunk" })
vim.keymap.set("n", "<leader>gl", function()
    require("gitsigns").blame_line()
end, { desc = "Blame Line" })
vim.keymap.set("n", "<leader>gr", function()
    require("gitsigns").reset_hunk()
end, { desc = "Reset Hunk" })
vim.keymap.set("n", "<leader>gs", function()
    require("gitsigns").stage_hunk()
end, { desc = "Stage Hunk" })
vim.keymap.set("n", "<leader>gu", function()
    require("gitsigns").undo_stage_hunk()
end, { desc = "Undo Stage Hunk" })
vim.keymap.set("n", "<leader>gp", function()
    require("gitsigns").preview_hunk()
end, { desc = "Undo Stage Hunk" })
-- R = { function() require('gitsigns').reset_buffer() end, 'Reset Buffer', },
