[pyprland]
plugins = ["magnify", "scratchpads", "toggle_special"]


[scratchpads.signal]
command = "HOME=$HOME/.local/xdg-launch signal-desktop"
class = "Signal"
size = "75% 90%"
animation = ""
lazy = true

[scratchpads.notes]
command = "emacs --name notes ~/documents/org/main.org"
class = "notes"
animation = ""
margin = 50
size = "90% 90%"
lazy = true

[scratchpads.cmus]
command = "kitty --class cmus -e cmus"
class = "cmus"
animation = ""
margin = 50
size = "90% 90%"
lazy = true


[scratchpads.spotify]
command = "xdg-launch spotify-launcher"
class = "spotify"
animation = ""
margin = 50
size = "90% 90%"
position = "5% 6%"
lazy = true
