[pyprland]
plugins = ["magnify", "scratchpads"]


[scratchpads.signal]
command = "HOME=$HOME/.local/xdg-garbage signal-desktop"
class = "Signal"
size = "75% 90%"
animation = ""
lazy = true

[scratchpads.notes]
command = "emacs --name notes ~/documents/org/main.org"
class = "notes"
animation = ""
margin = 50
size = "90% 90%"
max_size = "1920px 100%"
lazy = true
