#!/usr/bin/sh -e

if pgrep -x "lbrynet" >/dev/null
then
    lbrynet stop
    notify-send "lbrynet stopped."
else
    notify-send "Starting lbrynet..."
    nohup lbrynet start > $HOME/.local/share/lbry-nohup.out
fi
