#!/usr/bin/sh -e

if pgrep -x "mailspring" > /dev/null
then
    if wmctrl -l | grep "Mailspring > /dev/null"
    then
        i3-msg workspace 1:
    else
        i3-msg workspace 1:
        mailspring & disown
    fi
else
    i3-msg workspace 1:
    mailspring & disown
fi
