#!/usr/bin/bash -e

if pgrep -x "spotifyd" >/dev/null
then
    notify-send "Restarting spotifyd."
    killall spotifyd
    spotifyd & disown
else
    notify-send "Starting spotifyd."
    spotifyd & disown
fi
