#!/usr/bin/sh -e

# if pgrep -x "blah" > /dev/null
# then
#     i3-msg workspace 7
# else
#     i3-msg workspace 7
#     brave --profile-directory=Default --app-id=elldfnmogicegdcphgljaoaklkpcnbnn
# fi

i3-msg workspace 7
brave --profile-directory=Default --app-id=elldfnmogicegdcphgljaoaklkpcnbnn
