#! perl
#
sub on_user_command {
    my ($self, $cmd) = @_;

	    if ($cmd eq 'urxvt-colors:next') {
      $self->cmd_parse(`dynamic-colors next`);
	    }

	    if ($cmd eq 'urxvt-colors:previous') {
      $self->cmd_parse(`dynamic-colors previous`);
	    }
}
