#!/usr/bin/dash

activewindow=$(hyprctl activewindow)
group=$(echo "$activewindow" | grep -E "grouped: [^0$]")

if [ -z "$group" ]; then
	hyprctl dispatch movewindoworgroup "$1"
else
	window_id=$(echo "$activewindow" | grep -Eo 'Window [0-9a-f]+' | cut -d' ' -f2)
	if [ "$1" = "r" ]; then
		echo "$group" | grep -q "$window_id$" && hyprctl dispatch movewindoworgroup r || hyprctl dispatch movegroupwindow f
	elif [ "$1" = "l" ]; then
		echo "$group" | grep -q ": $window_id" && hyprctl dispatch movewindoworgroup l || hyprctl dispatch movegroupwindow b
	else
		hyprctl dispatch movewindoworgroup "$1"
	fi
fi
