# You can refer to the official documentation:
# https://espanso.org/docs/

toggle_key: OFF
fast_inject: true
undo_backspace: false

matches:
  # Simple text replacement
  - trigger: ";;ss"
    replace: "⊃"
  - trigger: ";;equiv"
    replace: "≡"
  - trigger: ";;lor"
    replace: "∨"
  - trigger: ";;xor"
    replace: "⊻"
  - trigger: ";;ts"
    replace: "⊢"
  - trigger: ";;dts"
    replace: "⊨"
  - trigger: ";;exists"
    replace: "∃"

  - trigger: ";ss"
    replace: "$\\supset$"
  - trigger: ";and"
    replace: "$\\&$"
  - trigger: ";or"
    replace: "$\\lor$"
  - trigger: ";equiv"
    replace: "$\\equiv$"
  - trigger: ";not"
    replace: "$\\sim$"
  - trigger: ";neq"
    replace: "$\\neq$"
  - trigger: ";exists"
    replace: "$\\exists$"

  - trigger: ";doto"
    replace: "ö"

  - trigger: ";-"
    replace: "—"
  - trigger: ";paragraph"
    replace: "¶"
  - trigger: ";silcrow"
    replace: "§"

  - trigger: ";thumbup"
    replace: "👍"

  # Dates
  - trigger: ";date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  # Shell commands
  - trigger: ";shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo Hello from your shell"
